### ISSUE TITLE
Live test does not work as expected for Torque

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#115]
After merging #106 into master, when I do this on webtest04 I get an error:

```
efranz@webtest04:~/dev/ood_core (master)$ export LIVE_CLUSTER_CONFIG=/etc/ood/config/clusters.d/owens.yml
efranz@webtest04:~/dev/ood_core (master)$ bundle exec rspec
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................FFFFF
Live system tests complete. Continuing with other tests:
.....................................................................................................................................

Failures:

  1) a live system can submit
     Failure/Error: adapter = c.fetch(:adapter) { raise AdapterNotSpecified, "job configuration does not specify adapter" }.to_s
     
     OodCore::AdapterNotSpecified:
       job configuration does not specify adapter
     # ./lib/ood_core/job/factory.rb:19:in `block in build'
     # ./lib/ood_core/job/factory.rb:19:in `fetch'
     # ./lib/ood_core/job/factory.rb:19:in `build'
     # ./spec/job/live_system_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) a live system can get info
     Failure/Error: adapter = c.fetch(:adapter) { raise AdapterNotSpecified, "job configuration does not specify adapter" }.to_s
     
     OodCore::AdapterNotSpecified:
       job configuration does not specify adapter
     # ./lib/ood_core/job/factory.rb:19:in `block in build'
     # ./lib/ood_core/job/factory.rb:19:in `fetch'
     # ./lib/ood_core/job/factory.rb:19:in `build'
     # ./spec/job/live_system_spec.rb:5:in `block (2 levels) in <top (required)>'

  3) a live system can get status
     Failure/Error: adapter = c.fetch(:adapter) { raise AdapterNotSpecified, "job configuration does not specify adapter" }.to_s
     
     OodCore::AdapterNotSpecified:
       job configuration does not specify adapter
     # ./lib/ood_core/job/factory.rb:19:in `block in build'
     # ./lib/ood_core/job/factory.rb:19:in `fetch'
     # ./lib/ood_core/job/factory.rb:19:in `build'
     # ./spec/job/live_system_spec.rb:5:in `block (2 levels) in <top (required)>'

  4) a live system can release a held job
     Failure/Error: adapter = c.fetch(:adapter) { raise AdapterNotSpecified, "job configuration does not specify adapter" }.to_s
     
     OodCore::AdapterNotSpecified:
       job configuration does not specify adapter
     # ./lib/ood_core/job/factory.rb:19:in `block in build'
     # ./lib/ood_core/job/factory.rb:19:in `fetch'
     # ./lib/ood_core/job/factory.rb:19:in `build'
     # ./spec/job/live_system_spec.rb:5:in `block (2 levels) in <top (required)>'

  5) a live system can delete a job
     Failure/Error: adapter = c.fetch(:adapter) { raise AdapterNotSpecified, "job configuration does not specify adapter" }.to_s
     
     OodCore::AdapterNotSpecified:
       job configuration does not specify adapter
     # ./lib/ood_core/job/factory.rb:19:in `block in build'
     # ./lib/ood_core/job/factory.rb:19:in `fetch'
     # ./lib/ood_core/job/factory.rb:19:in `build'
     # ./spec/job/live_system_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.29482 seconds (files took 0.72468 seconds to load)
647 examples, 5 failures

Failed examples:

rspec ./spec/job/live_system_spec.rb:36 # a live system can submit
rspec ./spec/job/live_system_spec.rb:41 # a live system can get info
rspec ./spec/job/live_system_spec.rb:46 # a live system can get status
rspec ./spec/job/live_system_spec.rb:54 # a live system can release a held job
rspec ./spec/job/live_system_spec.rb:61 # a live system can delete a job

```

I would expect that a live test would work as expected. What did I do wrong, or is it broken?

**Comment by ericfranz** [comment]
So the issue is that `OodCore::Job:Factory.build` expects a hash config for the job, not the entire cluster config. But the `YAML.load_file` is being called on `LIVE_CLUSTER_CONFIG`. A job config for a valid cluster config would be in the yaml file at:

```yaml
v2:
  job:
    # job config here
```

**Comment by ericfranz** [comment]
Fixed https://github.com/OSC/ood_core/commit/3fd3e2c9f7fbb776e101f2f40afdb028da0bb5ba
