### ISSUE TITLE
Slurm 19 Support

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ood_core#127]
Based on a failure in ActiveJobs Slurm 19 appears to have introduced another breaking change into `squeue`:

```
FATAL "NoMethodError (undefined method `to_sym' for nil:NilClass):\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/ood_core-0.8.0/lib/ood_core/cluster.rb:139:in `=='\n  /var/www/ood/apps/sys/activejobs/app/models/jobs_json_request_handler.rb:23:in `block in clusters'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/ood_core-0.8.0/lib/ood_core/clusters.rb:111:in `each'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/ood_core-0.8.0/lib/ood_core/clusters.rb:111:in `each'\n  /var/www/ood/apps/sys/activejobs/app/models/jobs_json_request_handler.rb:23:in `select'\n  /var/www/ood/apps/sys/activejobs/app/models/jobs_json_request_handler.rb:23:in `clusters'\n  /var/www/ood/apps/sys/activejobs/app/models/jobs_json_request_handler.rb:42:in `render'\n  /var/www/ood/apps/sys/activejobs/app/controllers/jobs_controller.rb:18:in `block (2 levels) in index'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/mime_responds.rb:217:in `respond_to'\n  /var/www/ood/apps/sys/activejobs/app/controllers/jobs_controller.rb:9:in `index'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/base.rb:198:in `process_action'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rendering.rb:10:in `process_action'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/callbacks.rb:20:in `block in process_action'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:117:in `call'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:505:in `call'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:92:in `__run_callbacks__'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/callbacks.rb:19:in `process_action'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rescue.rb:29:in `process_action'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `block in instrument'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `instrument'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:30:in `process_action'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/base.rb:137:in `process'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/rendering.rb:30:in `process'\n  /var/www/ood/apps/sys/activejobs/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/live.rb:278:in `block in process'"```

**Comment by MorganRodgers** [comment]
This issue was opened in error. The failure I saw was a result of a Firefox caching issue due to rebuilding my test VMs. Slurm 19 appears to be fully supported.
