### ISSUE TITLE
no implicit conversion of Symbol into Integer impossible to debug

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood_core#299]
I just wasted a lot of time trying to figure out what I was doing wrong.  To replicate: I had the `bc_osc_rstudio` app with some `local/` modifications for testing classes. The `local/submit.yml.erb` was throwing this out.  I'd wonder if the dashboard didn't clobber the original?  
 
```text
ERROR: TypeError - no implicit conversion of Symbol into Integer
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.12/gems/ood_core-0.17.1/lib/ood_core/job/adapters/kubernetes/batch.rb:194:in `generate_id_yml'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.12/gems/ood_core-0.17.1/lib/ood_core/job/adapters/kubernetes/batch.rb:47:in `submit'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.12/gems/ood_core-0.17.1/lib/ood_core/job/adapters/kubernetes.rb:55:in `submit'
/users/PZS0714/johrstrom/ondemand/misc/ondemand/apps/dashboard/app/models/batch_connect/session.rb:263:in `submit'
/users/PZS0714/johrstrom/ondemand/misc/ondemand/apps/dashboard/app/models/batch_connect/session.rb:216:in `save'
```

I was trying to do something like this.  The dashboard loading this and overriding the original seemed to really throw the this library through a loop. 

```erb
<%-
  k8s_classroom = [
    'PZS1010'
  ].any? { |prj| prj == account.to_s }
-%>
---
batch_connect:
  template: "basic"
script:
  accounting_id: "<%= account %>"
  # I tried several variations of this block here 1 line up, 2 lines up, etc. all the same.
  <%- unless k8s_classroom -%>  
  native:
    - "--nodes"
    - "1"
    - "--ntasks-per-node"
    - "<%= num_cores %>"
  <%- end -%>
```

**Comment by johrstrom** [comment]
We're changing this to instead add validation the submit method for all adapters to validate the `script#native` datatype to ensure it's the expected datatype. Hence the label change.

**Comment by johrstrom** [comment]
Just circling back to this as we review #763 that we likely need a checklist for the initial comment as we make PRs for all the schedulers.

**Comment by moffatsadeghi** [comment]
GitHub Review Meeting Summary from June: 
The team reviewed a recurring and difficult-to-debug type error encountered when developing BatchConnect apps, particularly with the Kubernetes adapter.
- Details
    - johrstrom: Described the error as a type mismatch where a symbol is passed where an integer or string is expected. The error surfaces far from its origin, making it hard to trace.
    - bsingleton: Explained the concept of Ruby symbols to Emily for context.
    - johrstrom: Noted the root cause is an array/hash mismatch across different adapters — some adapters use arrays, others use hashes, and Kubernetes only supports arrays.
    - bsingleton: Proposed that each adapter validate the input structure upfront and throw a clear error if the wrong type is passed, rather than failing silently downstream.
    - johrstrom: Confirmed that a previous ticket about unifying array/hash handling across adapters was likely closed without being scheduled.
    - bsingleton: Suggested broadening the scope of this ticket to cover all adapters rather than just Kubernetes, since the fix should be well-defined and not overly large.
    - Emily: Asked whether this affects system administrators; johrstrom and bsingleton confirmed it primarily affects app developers and generates support tickets.
    - johrstrom: Searched Discourse and found multiple hits for this error, confirming it is a recurring community pain point.
- Conclusion
    - Issue scope broadened to cover all adapters.
    - Marked as scheduled.
