### ISSUE TITLE
LHA and likely systemd don't respond to native arrays

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood_core#763]
Most adapters use an array for `#native` attributes. `linux_host` and likely `systemd` use hashes.

So when someone uses an array (like the dashboard's `test:jobs` rake task does) it throws this runtime error. 
```
rake aborted!
TypeError: no implicit conversion of String into Integer
/users/PZS0714/johrstrom/ondemand/src/apps/dashboard/vendor/bundle/ruby/2.7.0/gems/ood_core-0.20.0/lib/ood_core/job/adapters/linux_host/launcher.rb:97:in `[]'
/users/PZS0714/johrstrom/ondemand/src/apps/dashboard/vendor/bundle/ruby/2.7.0/gems/ood_core-0.20.0/lib/ood_core/job/adapters/linux_host/launcher.rb:97:in `submit_host'
/users/PZS0714/johrstrom/ondemand/src/apps/dashboard/vendor/bundle/ruby/2.7.0/gems/ood_core-0.20.0/lib/ood_core/job/adapters/linux_host/launcher.rb:60:in `start_remote_session'
/users/PZS0714/johrstrom/ondemand/src/apps/dashboard/vendor/bundle/ruby/2.7.0/gems/ood_core-0.20.0/lib/ood_core/job/adapters/linux_host.rb:83:in `submit'
```

These should be casting to hashes as arrays are more popular.

**Comment by johrstrom** [comment]
Closing this now as a duplicate/more specific version of #299.
